# Generated by Django 5.2.3 on 2025-07-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10),
        ),
    ]
