# Generated by Django 5.2.3 on 2026-08-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('ADMIN', 'ADMIN'), ('Teacher', 'Teacher')], max_length=10),
        ),
    ]
