# Generated by Django 5.2.3 on 2025-08-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('ADMIN', 'ADMIN'), ('Student', 'Student')], max_length=10),
        ),
    ]
