# Generated by Django 5.2.3 on 2025-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=10),
        ),
    ]
