# Generated by Django 5.2.3 on 2025-07-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
