# Generated by Django 5.2.3 on 2026-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
