# Generated by Django 5.2.3 on 2026-07-25 18:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_order_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
