# Generated by Django 5.2.3 on 2026-07-25 18:36

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_embedding'),
    ]

    operations = [
        VectorExtension()
    ]
