# Generated by Django 5.2.3 on 2026-07-25 18:38

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enable_pgvector'),
    ]

    operations = [
        VectorExtension()
    ]
