# Generated by Django 5.2.3 on 2026-07-25 19:21

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enable_pgvector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='lesson_index', opclasses=['vector_cosine_ops']),
        ),
    ]
