# Generated by Django 5.2.3 on 2026-07-25 20:20

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_lesson_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
