# Generated by Django 5.2.3 on 2026-08-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='done',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='done',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='done',
            new_name='is_published',
        ),
    ]
