# Generated by Django 5.2.3 on 2026-08-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lesson_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='lesson_index',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='embedding',
        ),
    ]
