# Generated by Django 6.1.1 on 2026-09-13 20:26

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_done_course_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', validators=[utils.validators.validate_file_type, utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='lesson_docs/', validators=[utils.validators.validate_file_type, utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_vids/', validators=[utils.validators.validate_file_type, utils.validators.validate_file_size]),
        ),
    ]
