# Generated by Django 6.1.1 on 2026-09-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticcache',
            name='course_ids',
            field=models.JSONField(default=list),
        ),
    ]
