# Generated by Django 5.2.3 on 2026-04-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_fix_useranswer_cascade_and_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
