# Generated by Django 6.1.1 on 2026-09-13 20:26

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(upload_to='assignment_docs/', validators=[utils.validators.validate_file_type, utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='submission_docs/', validators=[utils.validators.validate_file_type, utils.validators.validate_file_size]),
        ),
    ]
